nelmio_api_doc:
    documentation:
        info:
            title: HDPN API
            description: La Hotte du Père Noël
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: "Value: Bearer {jwt}"
                name: Authorization
                in: header
            security:
                - Bearer: []

        paths:
            ##### Accounts #####
            /api/login_check:
                post:
                    tags:
                        - Account
                    summary: "Allow anonymous user to login & obtain token"
                    parameters:
                        - in: body
                          name: body
                          required: true
                          schema:
                              $ref: "#/definitions/CredentialsInput"

                    responses:
                        200:
                            description: "Successful login"
                            schema:
                                $ref: "#/definitions/UserInfoOutput"
            /api/account/anon/create:
                post:
                    tags:
                        - Account
                    summary: "Allow anonymous user to create an account"
                    parameters:
                        - in: body
                          name: body
                          required: true
                          schema:
                              $ref: "#/definitions/CreateAccountInput"
                    responses:
                        201:
                            description: "Successful creation"
                        400:
                            description: "Bad request"
            #### Article ####
            /api/articles:
                post:
                    security:
                        - Bearer: []
                    tags:
                        - Article
                    summary: "Allow user to add an article to sell this"
                    parameters:
                        - in: body
                          name: body
                          required: true
                          schema:
                              $ref: "#/definitions/NewArticleInput"
                    responses:
                        201:
                            description: "Successful creation"
                            schema:
                                $ref: "#/definitions/ShortListArticleOut"
        definitions:
            ShortListArticleOut:
                type: array
                items:
                    $ref: "#/definitions/ArticleOut"
            ArticleOut:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    category:
                        type: object
                        $ref: "#/definitions/CategoryArticleOut"
                    age:
                        type: object
                        $ref: "#/definitions/AgeArticleOut"
                    description:
                        type: string
                    price:
                        type: number
                        required: true
                    ageMin:
                        type: integer
                    ageMax:
                        type: integer
                    gender:
                        type: string
                        required: true
                    createdAt:
                        type: string
                        format: datetime
                        example: "2019/09/21 10:00:00"
                    updatedAt:
                        type: string
                        format: datetime
                        example: "2019/09/21 10:00:00"
                    brand:
                        type: object
                        $ref: "#/definitions/BrandOut"
                    owner:
                        type: object
                        $ref: "#/definitions/UserOut"
                    images:
                        type: array
                        $ref: "#/definitions/ImageOut"
            CategoryArticleOut:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
            AgeArticleOut:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
            ImageOut:
                type: object
                properties:
                    id:
                        type: string
                    path:
                        type: string
            UserOut:
                type: object
                properties:
                    id:
                        type: string
                    username:
                        type: string

            BrandOut:
                type: object
                properties:
                    id:
                        type: string
                    name:
                        type: string
            NewArticleInput:
                type: object
                properties:
                    name:
                        type: string
                        required: true
                    category:
                        type: string
                        required: true
                        description: Uniq id of category
                    age:
                        type: string
                        required: true
                        description: Age targeted for this article
                    description:
                        type: string
                        required: false
                    price:
                        type: number
                        required: true
                    gender:
                        type: string
                        required: true
                        example: "boy, girl, mixed"
                    brand:
                        type: string
                        required: false
                    images:
                        type: array
                        required: false
                        items:
                            $ref: "#/definitions/ImageInput"

            ImageInput:
                type: object
                properties:
                    image:
                        type: string
                        format: byte
                        required: true
            CreateAccountInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            CredentialsInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            UserInfoOutput:
                type: object
                properties:
                    firstname:
                        type: string
                        required: false
                    lastname:
                        type: string
                        required: false
                    username:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
                    gender:
                        type: string
                        required: false
                    token:
                        type: string
                        required: true
                    refresh_token:
                        type: string
                        required: true
                    token_ttl:
                        type: integer
                        required: true
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - /api/doc.json
